// Code generated by protoc-gen-go. DO NOT EDIT.
// source: block.proto

/*
Package types is a generated protocol buffer package.

It is generated from these files:
	block.proto

It has these top-level messages:
	GenerateRequest
	GenerateResponse
*/
package types

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type GenerateRequest struct {
	Payload []byte `protobuf:"bytes,1,opt,name=Payload,proto3" json:"Payload,omitempty"`
}

func (m *GenerateRequest) Reset()                    { *m = GenerateRequest{} }
func (m *GenerateRequest) String() string            { return proto.CompactTextString(m) }
func (*GenerateRequest) ProtoMessage()               {}
func (*GenerateRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *GenerateRequest) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

type GenerateResponse struct {
	Md5 string `protobuf:"bytes,1,opt,name=Md5" json:"Md5,omitempty"`
	Id  []byte `protobuf:"bytes,2,opt,name=Id,proto3" json:"Id,omitempty"`
}

func (m *GenerateResponse) Reset()                    { *m = GenerateResponse{} }
func (m *GenerateResponse) String() string            { return proto.CompactTextString(m) }
func (*GenerateResponse) ProtoMessage()               {}
func (*GenerateResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *GenerateResponse) GetMd5() string {
	if m != nil {
		return m.Md5
	}
	return ""
}

func (m *GenerateResponse) GetId() []byte {
	if m != nil {
		return m.Id
	}
	return nil
}

func init() {
	proto.RegisterType((*GenerateRequest)(nil), "types.GenerateRequest")
	proto.RegisterType((*GenerateResponse)(nil), "types.GenerateResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for BlockGenerator service

type BlockGeneratorClient interface {
	Generate(ctx context.Context, in *GenerateRequest, opts ...grpc.CallOption) (*GenerateResponse, error)
}

type blockGeneratorClient struct {
	cc *grpc.ClientConn
}

func NewBlockGeneratorClient(cc *grpc.ClientConn) BlockGeneratorClient {
	return &blockGeneratorClient{cc}
}

func (c *blockGeneratorClient) Generate(ctx context.Context, in *GenerateRequest, opts ...grpc.CallOption) (*GenerateResponse, error) {
	out := new(GenerateResponse)
	err := grpc.Invoke(ctx, "/types.BlockGenerator/Generate", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for BlockGenerator service

type BlockGeneratorServer interface {
	Generate(context.Context, *GenerateRequest) (*GenerateResponse, error)
}

func RegisterBlockGeneratorServer(s *grpc.Server, srv BlockGeneratorServer) {
	s.RegisterService(&_BlockGenerator_serviceDesc, srv)
}

func _BlockGenerator_Generate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlockGeneratorServer).Generate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/types.BlockGenerator/Generate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlockGeneratorServer).Generate(ctx, req.(*GenerateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _BlockGenerator_serviceDesc = grpc.ServiceDesc{
	ServiceName: "types.BlockGenerator",
	HandlerType: (*BlockGeneratorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Generate",
			Handler:    _BlockGenerator_Generate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "block.proto",
}

func init() { proto.RegisterFile("block.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 160 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4e, 0xca, 0xc9, 0x4f,
	0xce, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2d, 0xa9, 0x2c, 0x48, 0x2d, 0x56, 0xd2,
	0xe6, 0xe2, 0x77, 0x4f, 0xcd, 0x4b, 0x2d, 0x4a, 0x2c, 0x49, 0x0d, 0x4a, 0x2d, 0x2c, 0x4d, 0x2d,
	0x2e, 0x11, 0x92, 0xe0, 0x62, 0x0f, 0x48, 0xac, 0xcc, 0xc9, 0x4f, 0x4c, 0x91, 0x60, 0x54, 0x60,
	0xd4, 0xe0, 0x09, 0x82, 0x71, 0x95, 0x4c, 0xb8, 0x04, 0x10, 0x8a, 0x8b, 0x0b, 0xf2, 0xf3, 0x8a,
	0x53, 0x85, 0x04, 0xb8, 0x98, 0x7d, 0x53, 0x4c, 0xc1, 0x2a, 0x39, 0x83, 0x40, 0x4c, 0x21, 0x3e,
	0x2e, 0x26, 0xcf, 0x14, 0x09, 0x26, 0xb0, 0x56, 0x26, 0xcf, 0x14, 0x23, 0x7f, 0x2e, 0x3e, 0x27,
	0x90, 0xc5, 0x50, 0xad, 0xf9, 0x45, 0x42, 0xb6, 0x5c, 0x1c, 0x30, 0x73, 0x84, 0xc4, 0xf4, 0xc0,
	0x0e, 0xd1, 0x43, 0x73, 0x85, 0x94, 0x38, 0x86, 0x38, 0xc4, 0x42, 0x25, 0x86, 0x24, 0x36, 0xb0,
	0x0f, 0x8c, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0xb8, 0x38, 0xc5, 0xe7, 0xd0, 0x00, 0x00, 0x00,
}
